Added contents to Readme.md
FOSSersVAST/vaasu pull request #4
Opened 2019-11-09 08:54 UTC by ARJUNRAGHUNANDANAN

2019-11-09 19:37 UTC, subins2000 requested changes

2019-11-09 19:37 UTC, subins2000 commented on README.md
> +you can find the original repository in the link
No need of this

2019-11-09 19:37 UTC, subins2000 commented on README.md
> +It is an Open source Project currently bring developed for Vidya Academy of Science and Technology by FossersVAST
typo "being"

FOSSersVAST (notice the letter capitalizations)

2019-11-09 19:37 UTC, subins2000 commented on README.md
> +The attendence data is will be as recieved from the student's college ERP
typos

2019-11-16 15:23 UTC, abspython commented
I think we could complete the README after finishing the project.

2019-11-16 15:27 UTC, subins2000 commented
@abspython We can have a todo list or something in the readme for tracking maybe ?

2019-12-21 18:48 UTC, merged